Allow null authors in metadata.yaml
Previousely, the following metadata.yaml would cause the following exception:

```yaml
title: "Title"
lang: en-US
author_info:
```

```
  File "manubot/process/util.py", line 199, in get_metadata_and_variables
    metadata['author-meta'] = [author['name'] for author in authors]
TypeError: 'NoneType' object is not iterable
```

Instead, we should treat null authors field as an empty array/list.