restore setup.py
setup.py is required for pip install --editable

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/dhimmel/Documents/repos/manubot
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

Also using `python setup.py --version` in readme.