Remove requests-cache due to Travis CI error
See https://travis-ci.org/greenelab/manubot/builds/258991246#L556

```
error: The 'requests' distribution was not found and is required by manubot
```